// Code generated by MockGen. DO NOT EDIT.
// Source: ../../infrastructure/capa/capa.go
//
// Generated by this command:
//
//	mockgen -package mocks -destination=./mock_capa.go -source=../../infrastructure/capa/capa.go -build_flags=-mod=mod
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	infrastructure "github.com/platform9/cluster-api-sdk-go/infrastructure"
	gomock "go.uber.org/mock/gomock"
	v1beta2 "sigs.k8s.io/cluster-api-provider-aws/v2/api/v1beta2"
)

// MockAWSProvider is a mock of AWSProvider interface.
type MockAWSProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAWSProviderMockRecorder
}

// MockAWSProviderMockRecorder is the mock recorder for MockAWSProvider.
type MockAWSProviderMockRecorder struct {
	mock *MockAWSProvider
}

// NewMockAWSProvider creates a new mock instance.
func NewMockAWSProvider(ctrl *gomock.Controller) *MockAWSProvider {
	mock := &MockAWSProvider{ctrl: ctrl}
	mock.recorder = &MockAWSProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSProvider) EXPECT() *MockAWSProviderMockRecorder {
	return m.recorder
}

// CreateClusterRoleIdentity mocks base method.
func (m *MockAWSProvider) CreateClusterRoleIdentity(ctx context.Context, input infrastructure.CreateInfraClusterIdentityInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClusterRoleIdentity", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateClusterRoleIdentity indicates an expected call of CreateClusterRoleIdentity.
func (mr *MockAWSProviderMockRecorder) CreateClusterRoleIdentity(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClusterRoleIdentity", reflect.TypeOf((*MockAWSProvider)(nil).CreateClusterRoleIdentity), ctx, input)
}

// CreateInfraCluster mocks base method.
func (m *MockAWSProvider) CreateInfraCluster(ctx context.Context, input infrastructure.CreateInfraClusterInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInfraCluster", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInfraCluster indicates an expected call of CreateInfraCluster.
func (mr *MockAWSProviderMockRecorder) CreateInfraCluster(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInfraCluster", reflect.TypeOf((*MockAWSProvider)(nil).CreateInfraCluster), ctx, input)
}

// CreateInfraMachine mocks base method.
func (m *MockAWSProvider) CreateInfraMachine(ctx context.Context, input infrastructure.CreateInfraMachineInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInfraMachine", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInfraMachine indicates an expected call of CreateInfraMachine.
func (mr *MockAWSProviderMockRecorder) CreateInfraMachine(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInfraMachine", reflect.TypeOf((*MockAWSProvider)(nil).CreateInfraMachine), ctx, input)
}

// CreateInfraMachineTemplate mocks base method.
func (m *MockAWSProvider) CreateInfraMachineTemplate(ctx context.Context, input infrastructure.CreateInfraMachineTemplateInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInfraMachineTemplate", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInfraMachineTemplate indicates an expected call of CreateInfraMachineTemplate.
func (mr *MockAWSProviderMockRecorder) CreateInfraMachineTemplate(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInfraMachineTemplate", reflect.TypeOf((*MockAWSProvider)(nil).CreateInfraMachineTemplate), ctx, input)
}

// CreateInfraStaticIdentity mocks base method.
func (m *MockAWSProvider) CreateInfraStaticIdentity(ctx context.Context, input infrastructure.CreateInfraClusterIdentityInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInfraStaticIdentity", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInfraStaticIdentity indicates an expected call of CreateInfraStaticIdentity.
func (mr *MockAWSProviderMockRecorder) CreateInfraStaticIdentity(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInfraStaticIdentity", reflect.TypeOf((*MockAWSProvider)(nil).CreateInfraStaticIdentity), ctx, input)
}

// CreateSecretForAWSSI mocks base method.
func (m *MockAWSProvider) CreateSecretForAWSSI(ctx context.Context, input infrastructure.CreateInfraClusterIdentityInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecretForAWSSI", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecretForAWSSI indicates an expected call of CreateSecretForAWSSI.
func (mr *MockAWSProviderMockRecorder) CreateSecretForAWSSI(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecretForAWSSI", reflect.TypeOf((*MockAWSProvider)(nil).CreateSecretForAWSSI), ctx, input)
}

// DeleteClusterRoleIdentity mocks base method.
func (m *MockAWSProvider) DeleteClusterRoleIdentity(ctx context.Context, input infrastructure.DeleteInfraClusterIdentityInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClusterRoleIdentity", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClusterRoleIdentity indicates an expected call of DeleteClusterRoleIdentity.
func (mr *MockAWSProviderMockRecorder) DeleteClusterRoleIdentity(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClusterRoleIdentity", reflect.TypeOf((*MockAWSProvider)(nil).DeleteClusterRoleIdentity), ctx, input)
}

// DeleteInfraCluster mocks base method.
func (m *MockAWSProvider) DeleteInfraCluster(ctx context.Context, input infrastructure.DeleteInfraClusterInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInfraCluster", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInfraCluster indicates an expected call of DeleteInfraCluster.
func (mr *MockAWSProviderMockRecorder) DeleteInfraCluster(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInfraCluster", reflect.TypeOf((*MockAWSProvider)(nil).DeleteInfraCluster), ctx, input)
}

// DeleteInfraMachine mocks base method.
func (m *MockAWSProvider) DeleteInfraMachine(ctx context.Context, input infrastructure.DeleteInfraMachineInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInfraMachine", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInfraMachine indicates an expected call of DeleteInfraMachine.
func (mr *MockAWSProviderMockRecorder) DeleteInfraMachine(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInfraMachine", reflect.TypeOf((*MockAWSProvider)(nil).DeleteInfraMachine), ctx, input)
}

// DeleteInfraMachineTemplate mocks base method.
func (m *MockAWSProvider) DeleteInfraMachineTemplate(ctx context.Context, input infrastructure.DeleteInfraMachineTemplateInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInfraMachineTemplate", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInfraMachineTemplate indicates an expected call of DeleteInfraMachineTemplate.
func (mr *MockAWSProviderMockRecorder) DeleteInfraMachineTemplate(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInfraMachineTemplate", reflect.TypeOf((*MockAWSProvider)(nil).DeleteInfraMachineTemplate), ctx, input)
}

// DeleteInfraStaticIdentity mocks base method.
func (m *MockAWSProvider) DeleteInfraStaticIdentity(ctx context.Context, input infrastructure.DeleteInfraClusterIdentityInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInfraStaticIdentity", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInfraStaticIdentity indicates an expected call of DeleteInfraStaticIdentity.
func (mr *MockAWSProviderMockRecorder) DeleteInfraStaticIdentity(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInfraStaticIdentity", reflect.TypeOf((*MockAWSProvider)(nil).DeleteInfraStaticIdentity), ctx, input)
}

// DeleteSecretForAWSSI mocks base method.
func (m *MockAWSProvider) DeleteSecretForAWSSI(ctx context.Context, input infrastructure.CreateInfraClusterIdentityInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecretForAWSSI", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecretForAWSSI indicates an expected call of DeleteSecretForAWSSI.
func (mr *MockAWSProviderMockRecorder) DeleteSecretForAWSSI(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecretForAWSSI", reflect.TypeOf((*MockAWSProvider)(nil).DeleteSecretForAWSSI), ctx, input)
}

// GetClusterRoleIdentity mocks base method.
func (m *MockAWSProvider) GetClusterRoleIdentity(ctx context.Context, input infrastructure.GetInfraClusterIdentityInput) (*v1beta2.AWSClusterRoleIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterRoleIdentity", ctx, input)
	ret0, _ := ret[0].(*v1beta2.AWSClusterRoleIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterRoleIdentity indicates an expected call of GetClusterRoleIdentity.
func (mr *MockAWSProviderMockRecorder) GetClusterRoleIdentity(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterRoleIdentity", reflect.TypeOf((*MockAWSProvider)(nil).GetClusterRoleIdentity), ctx, input)
}

// GetInfraCluster mocks base method.
func (m *MockAWSProvider) GetInfraCluster(ctx context.Context, input infrastructure.GetInfraClusterInput) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfraCluster", ctx, input)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfraCluster indicates an expected call of GetInfraCluster.
func (mr *MockAWSProviderMockRecorder) GetInfraCluster(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfraCluster", reflect.TypeOf((*MockAWSProvider)(nil).GetInfraCluster), ctx, input)
}

// GetInfraMachine mocks base method.
func (m *MockAWSProvider) GetInfraMachine(ctx context.Context, input infrastructure.GetInfraMachineInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfraMachine", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetInfraMachine indicates an expected call of GetInfraMachine.
func (mr *MockAWSProviderMockRecorder) GetInfraMachine(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfraMachine", reflect.TypeOf((*MockAWSProvider)(nil).GetInfraMachine), ctx, input)
}

// GetInfraMachineTemplate mocks base method.
func (m *MockAWSProvider) GetInfraMachineTemplate(ctx context.Context, input infrastructure.GetInfraMachineTemplateInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfraMachineTemplate", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetInfraMachineTemplate indicates an expected call of GetInfraMachineTemplate.
func (mr *MockAWSProviderMockRecorder) GetInfraMachineTemplate(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfraMachineTemplate", reflect.TypeOf((*MockAWSProvider)(nil).GetInfraMachineTemplate), ctx, input)
}
